name: Build-Windows

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.PRIVATE_TOKEN }}

    - uses: lukka/get-cmake@latest
    # Setup vcpkg: ensures vcpkg is downloaded and built.
    # Since vcpkg.json is being used later on to install the packages
    # when `run-cmake` runs, no packages are installed at this time
    # (and vcpkg does not run).
    - name: Setup anew (or from cache) vcpkg (and does not build any package)
      uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                # action you need, `v11` in this case to stay up
                                # to date with fixes on the v11 branch.
      with:
        vcpkgGitCommitId: "055721089e8037d4d617250814d11f881e557549"
        vcpkgJsonGlob: "vcpkg.json"
        VCPKGCONFIGURATIONJSONGLOB: "vcpkg-configuration.json"

    - name: Build
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "windows-latest"
        path: build/Windows/bin
        retention-days: 14
